#!/usr/bin/env bash
# Regenerate the checked-in bindings in src/bindings/.
#
# The RKLLM header is not vendored: the generated bindings are what this crate
# ships, and the header is only needed to produce them. It is fetched into a
# temporary directory, used, and thrown away. Each generated file records the
# source and the SHA-256 of the header it came from.
#
# Requires: bindgen-cli (cargo install bindgen-cli), libclang, curl.
#
#   ./regen-bindings.sh                       # fetch from upstream main
#   RKLLM_HEADER_REF=v1.2.1 ./regen-bindings.sh   # fetch a tag or commit
#   RKLLM_HEADER=/path/to/rkllm.h ./regen-bindings.sh   # use a local copy
set -euo pipefail

cd "$(dirname "$0")"

REF="${RKLLM_HEADER_REF:-main}"
URL="https://raw.githubusercontent.com/airockchip/rknn-llm/${REF}/rkllm-runtime/Linux/librkllm_api/include/rkllm.h"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

if [[ -n "${RKLLM_HEADER:-}" ]]; then
  cp "$RKLLM_HEADER" "$WORK/rkllm.h"
  SOURCE="$RKLLM_HEADER"
else
  curl -sSfL -o "$WORK/rkllm.h" "$URL"
  SOURCE="$URL"
fi

SHA="$(sha256sum "$WORK/rkllm.h" | cut -d' ' -f1)"

# rkllm.h uses size_t but includes only <cstdint>, which does not declare it,
# so it does not parse on its own. Pull in <cstddef> first and leave the header
# itself untouched. It is C++ despite the extern "C" block.
cat > "$WORK/wrapper.h" <<'WRAPPER'
#include <cstddef>
#include <cstdint>

#include "rkllm.h"
WRAPPER

HEADER="$WORK/wrapper.h"
OUT=src/bindings

COMMON=(
  --allowlist-file '.*rkllm\.h'
  --no-layout-tests
  --default-enum-style newtype
  --sort-semantically
  --merge-extern-blocks
)
CLANG=(-x c++ -std=c++17)

ALLOW='#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(clippy::missing_safety_doc)]
#![allow(rustdoc::broken_intra_doc_links)]'
WARN="// @generated by regen-bindings.sh -- do not edit by hand.
// Source: $SOURCE
// sha256: $SHA"

bindgen "$HEADER" "${COMMON[@]}" \
  --blocklist-function '.*' \
  --raw-line '//! C types of the RKLLM runtime.' \
  --raw-line "$ALLOW" \
  --raw-line "$WARN" \
  -o "$OUT/types.rs" -- "${CLANG[@]}"

bindgen "$HEADER" "${COMMON[@]}" \
  --allowlist-function 'rkllm_.*' \
  --blocklist-type '.*' --blocklist-var '.*' \
  --raw-line '//! Link-time bindings: the symbols are resolved by the linker against `librkllmrt`.' \
  --raw-line "$ALLOW" \
  --raw-line "$WARN" \
  --raw-line 'use super::types::*;' \
  -o "$OUT/link.rs" -- "${CLANG[@]}"

bindgen "$HEADER" "${COMMON[@]}" \
  --allowlist-function 'rkllm_.*' \
  --blocklist-type '.*' --blocklist-var '.*' \
  --dynamic-loading RkllmRuntime --dynamic-link-require-all \
  --raw-line '//! Runtime bindings: the symbols are resolved by `dlopen`/`libloading` at run time.' \
  --raw-line "$ALLOW" \
  --raw-line "// bindgen's --dynamic-loading output predates edition 2024's stricter unsafe rules." \
  --raw-line '#![allow(unsafe_op_in_unsafe_fn)]' \
  --raw-line "$WARN" \
  --raw-line 'use super::types::*;' \
  -o "$OUT/runtime.rs" -- "${CLANG[@]}"

echo "regenerated $OUT/{types,link,runtime}.rs with $(bindgen --version)"
echo "  source: $SOURCE"
echo "  sha256: $SHA"
