#!/usr/bin/env bash
# Regenerate the checked-in bindings in src/bindings/ from vendor/rkllm.h.
#
# Requires: bindgen-cli (cargo install bindgen-cli) and libclang.
# Run from the rkllm-sys crate root: ./regen-bindings.sh
set -euo pipefail

cd "$(dirname "$0")"

HEADER=vendor/wrapper.h
OUT=src/bindings

COMMON=(
  --allowlist-file '.*rkllm\.h'
  --no-layout-tests
  --default-enum-style newtype
  --sort-semantically
  --merge-extern-blocks
)
CLANG=(-x c++ -std=c++17)

ALLOW='#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(clippy::missing_safety_doc)]
#![allow(rustdoc::broken_intra_doc_links)]'
WARN='// @generated by regen-bindings.sh -- do not edit by hand.'

bindgen "$HEADER" "${COMMON[@]}" \
  --blocklist-function '.*' \
  --raw-line '//! C types of the RKLLM runtime, generated from `vendor/rkllm.h`.' \
  --raw-line "$ALLOW" \
  --raw-line "$WARN" \
  -o "$OUT/types.rs" -- "${CLANG[@]}"

bindgen "$HEADER" "${COMMON[@]}" \
  --allowlist-function 'rkllm_.*' \
  --blocklist-type '.*' --blocklist-var '.*' \
  --raw-line '//! Link-time bindings: the symbols are resolved by the linker against `librkllmrt`.' \
  --raw-line "$ALLOW" \
  --raw-line "$WARN" \
  --raw-line 'use super::types::*;' \
  -o "$OUT/link.rs" -- "${CLANG[@]}"

bindgen "$HEADER" "${COMMON[@]}" \
  --allowlist-function 'rkllm_.*' \
  --blocklist-type '.*' --blocklist-var '.*' \
  --dynamic-loading RkllmRuntime --dynamic-link-require-all \
  --raw-line '//! Runtime bindings: the symbols are resolved by `dlopen`/`libloading` at run time.' \
  --raw-line "$ALLOW" \
  --raw-line '// bindgen'"'"'s --dynamic-loading output predates edition 2024'"'"'s stricter unsafe rules.' \
  --raw-line '#![allow(unsafe_op_in_unsafe_fn)]' \
  --raw-line "$WARN" \
  --raw-line 'use super::types::*;' \
  -o "$OUT/runtime.rs" -- "${CLANG[@]}"

echo "regenerated $OUT/{types,link,runtime}.rs with $(bindgen --version)"
