//! Raw FFI bindings to `librkllmrt`, the Rockchip RKLLM runtime for RK3588 and
//! related NPUs.
//!
//! The bindings are checked in, generated by bindgen from the vendored
//! `rkllm.h`, and come in two flavours that share one trait:
//!
//! | Flavour | Feature | Symbols resolved |
//! |---|---|---|
//! | [`Linked`] | `link` (default) | by the linker, at build time |
//! | [`RkllmRuntime`] | `libloading` | by `dlopen`, at run time |
//!
//! Both implement [`RkllmApi`], so a caller can be generic over which one it
//! got. Everything here is `unsafe` and maps one-to-one onto the C API. The
//! safe wrapper lives in the `rkllm` crate.
//!
//! # Linking
//!
//! With the `link` feature the build script asks the linker for `rkllmrt`. Set
//! `RKLLM_LIB_DIR` to the directory holding `librkllmrt.so` if it is not on the
//! default search path.
//!
//! # Regenerating
//!
//! Run `./regen-bindings.sh` in this crate, which needs `bindgen-cli` and
//! libclang. The vendored header is `vendor/rkllm.h`.

mod bindings;

pub use bindings::*;

/// The runtime's shared object name, for use with [`RkllmRuntime::new`].
pub const LIBRARY_NAME: &str = "librkllmrt.so";

#[cfg(test)]
mod tests {
    use super::*;

    /// Both binding flavours must satisfy the one trait, and it must stay
    /// usable behind a `dyn` pointer so callers can pick at run time.
    #[test]
    fn both_flavours_implement_the_api() {
        fn assert_impl<T: RkllmApi>() {}

        #[cfg(feature = "link")]
        {
            assert_impl::<Linked>();
            let _: &dyn RkllmApi = &Linked::new();
        }

        #[cfg(feature = "libloading")]
        assert_impl::<RkllmRuntime>();

        fn _object_safe(_: &dyn RkllmApi) {}
    }
}
