//! Raw FFI bindings to `librkllmrt`, the Rockchip RKLLM runtime for RK3588 and
//! related NPUs.
//!
//! The bindings are checked in, generated by bindgen from Rockchip's
//! `rkllm.h`, and come in two flavours that share one trait:
//!
//! | Flavour | Feature | Symbols resolved |
//! |---|---|---|
//! | [`RkllmRuntime`] | `libloading` (default) | by `dlopen`, at run time |
//! | [`RkllmStatic`] | `link` | by the linker, at build time |
//!
//! Both implement [`RkllmApi`], so a caller can be generic over which one it
//! got. Everything here is `unsafe` and maps one-to-one onto the C API. The
//! safe wrapper lives in the `rkllm` crate.
//!
//! # Finding the runtime
//!
//! The default `libloading` feature resolves nothing at build time, so a build
//! needs no `librkllmrt` at all. Load it at run time with
//! [`RkllmRuntime::new`], passing a path or [`LIBRARY_NAME`].
//!
//! With the `link` feature instead, the build script asks the linker for
//! `rkllmrt`. Set `RKLLM_LIB_DIR` to the directory holding `librkllmrt.so` if
//! it is not on the default search path.
//!
//! # Regenerating
//!
//! Run `./regen-bindings.sh` in this crate, which needs `bindgen-cli`,
//! libclang and curl. The header is not vendored: the script fetches it into a
//! temporary directory, and each generated file records the source URL and the
//! SHA-256 of the header it came from. Set `RKLLM_HEADER_REF` to pin a tag or
//! commit, or `RKLLM_HEADER` to point at a local copy.

mod bindings;

pub use bindings::*;

/// The `libloading` crate the runtime bindings are built on, re-exported so
/// that dependents can name its error type without depending on it directly.
#[cfg(feature = "libloading")]
pub use libloading;

/// The runtime's shared object name, for use with [`RkllmRuntime::new`].
pub const LIBRARY_NAME: &str = "librkllmrt.so";

#[cfg(test)]
mod tests {
    use super::*;

    /// Both binding flavours must satisfy the one trait, and it must stay
    /// usable behind a `dyn` pointer so callers can pick at run time.
    #[test]
    fn both_flavours_implement_the_api() {
        fn assert_impl<T: RkllmApi>() {}

        #[cfg(feature = "link")]
        {
            assert_impl::<RkllmStatic>();
            let _: &dyn RkllmApi = &RkllmStatic::new();
        }

        #[cfg(feature = "libloading")]
        assert_impl::<RkllmRuntime>();

        fn _object_safe(_: &dyn RkllmApi) {}
    }
}
