//! Raw FFI bindings to `librkllmrt`, the Rockchip RKLLM runtime for RK3588 and
//! related NPUs.
//!
//! The bindings are checked in, generated by bindgen from Rockchip's
//! `rkllm.h`, and come in two flavours that share one trait:
//!
//! | Flavour | Feature | Symbols resolved |
//! |---|---|---|
//! | [`RkllmRuntime`] | `libloading` (default) | by `dlopen`, at run time |
//! | [`RkllmStatic`] | `link` | by the linker, at build time |
//!
//! Both implement [`RkllmApi`], so a caller can be generic over which one it
//! got. Everything here is `unsafe` and maps one-to-one onto the C API. The
//! safe wrapper lives in the `rkllm` crate.
//!
//! # Finding the runtime
//!
//! The default `libloading` feature resolves nothing at build time, so a build
//! needs no `librkllmrt` at all. Load it at run time with
//! [`RkllmRuntime::new`], passing a path or [`LIBRARY_NAME`].
//!
//! With the `link` feature instead, the build script asks the linker for
//! `rkllmrt`. Set `RKLLM_LIB_DIR` to the directory holding `librkllmrt.so` if
//! it is not on the default search path.
//!
//! # Regenerating
//!
//! Run `./regen-bindings.sh` in this crate, which needs `bindgen-cli`,
//! libclang and curl. The header is not vendored: the script fetches it into a
//! temporary directory, and each generated file records the source URL and the
//! SHA-256 of the header it came from. Set `RKLLM_HEADER_REF` to pin a tag or
//! commit, or `RKLLM_HEADER` to point at a local copy.

mod bindings;
mod find;

pub use bindings::*;
pub use find::find_library_path;

/// The `libloading` crate the runtime bindings are built on, re-exported so
/// that dependents can name its error type without depending on it directly.
#[cfg(feature = "libloading")]
pub use libloading;

/// The runtime's shared object name, for use with [`RkllmRuntime::new`].
pub const LIBRARY_NAME: &str = "librkllmrt.so";

#[cfg(test)]
mod tests {
    #[cfg(any(feature = "link", feature = "libloading"))]
    use super::*;

    #[cfg(any(feature = "link", feature = "libloading"))]
    fn assert_impl<T: RkllmApi>() {}

    /// The linked flavour must satisfy the trait, and it must stay usable
    /// behind a `dyn` pointer so callers can pick at run time.
    #[cfg(feature = "link")]
    #[test]
    fn the_linked_flavour_implements_the_api() {
        assert_impl::<RkllmStatic>();
        let _: &dyn RkllmApi = &RkllmStatic::new();
    }

    /// The runtime-loaded flavour must satisfy the same trait.
    #[cfg(feature = "libloading")]
    #[test]
    fn the_runtime_flavour_implements_the_api() {
        assert_impl::<RkllmRuntime>();
    }

    /// Wrappers forward, so a shared library can back several sessions.
    #[cfg(feature = "libloading")]
    #[test]
    fn wrappers_forward_the_api() {
        assert_impl::<std::sync::Arc<RkllmRuntime>>();
        assert_impl::<Box<dyn RkllmApi>>();
    }
}
