/* automatically generated by rust-bindgen 0.73.2 */

//! Link-time bindings: the symbols are resolved by the linker against `librkllmrt`.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(clippy::missing_safety_doc)]
#![allow(rustdoc::broken_intra_doc_links)]
// @generated by regen-bindings.sh -- do not edit by hand.
use super::types::*;

unsafe extern "C" {
    #[doc = " @brief Creates a default RKLLMParam structure with preset values.\n @return A default RKLLMParam structure."]
    pub fn rkllm_createDefaultParam() -> RKLLMParam;
    #[doc = " @brief Initializes the LLM with the given parameters.\n @param handle Pointer to the LLM handle.\n @param param Configuration parameters for the LLM.\n @param callback Pointer to callback structure for LLM events.\n @return Status code (0 for success, non-zero for failure)."]
    pub fn rkllm_init(
        handle: *mut LLMHandle,
        param: *mut RKLLMParam,
        callback: *mut RKLLMCallback,
    ) -> ::std::os::raw::c_int;
    #[doc = " @brief Loads a Lora adapter into the LLM.\n @param handle LLM handle.\n @param lora_adapter Pointer to the Lora adapter structure.\n @return Status code (0 for success, non-zero for failure)."]
    pub fn rkllm_load_lora(
        handle: LLMHandle,
        lora_adapter: *mut RKLLMLoraAdapter,
    ) -> ::std::os::raw::c_int;
    #[doc = " @brief Loads a prompt cache from a file.\n @param handle LLM handle.\n @param prompt_cache_path Path to the prompt cache file.\n @return Status code (0 for success, non-zero for failure)."]
    pub fn rkllm_load_prompt_cache(
        handle: LLMHandle,
        prompt_cache_path: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
    #[doc = " @brief Releases the prompt cache from memory.\n @param handle LLM handle.\n @return Status code (0 for success, non-zero for failure)."]
    pub fn rkllm_release_prompt_cache(handle: LLMHandle) -> ::std::os::raw::c_int;
    #[doc = " @brief Destroys the LLM instance and releases resources.\n @param handle LLM handle.\n @return Status code (0 for success, non-zero for failure)."]
    pub fn rkllm_destroy(handle: LLMHandle) -> ::std::os::raw::c_int;
    #[doc = " @brief Runs an LLM inference task synchronously.\n @param handle LLM handle.\n @param rkllm_input Input data for the LLM.\n @param rkllm_infer_params Parameters for the inference task.\n @param userdata Pointer to userdata for the result callback.\n        If userdata is not NULL, it will be used preferentially.\n        Otherwise, result_userdata will be used as fallback.\n @return Status code (0 for success, non-zero for failure)."]
    pub fn rkllm_run(
        handle: LLMHandle,
        rkllm_input: *mut RKLLMInput,
        rkllm_infer_params: *mut RKLLMInferParam,
        userdata: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
    #[doc = " @brief Runs an LLM inference task asynchronously.\n @param handle LLM handle.\n @param rkllm_input Input data for the LLM.\n @param rkllm_infer_params Parameters for the inference task.\n @param userdata Pointer to userdata for the result callback.\n        If userdata is not NULL, it will be used preferentially.\n        Otherwise, result_userdata will be used as fallback.\n @return Status code (0 for success, non-zero for failure)."]
    pub fn rkllm_run_async(
        handle: LLMHandle,
        rkllm_input: *mut RKLLMInput,
        rkllm_infer_params: *mut RKLLMInferParam,
        userdata: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
    #[doc = " @brief Aborts an ongoing LLM task.\n @param handle LLM handle.\n @return Status code (0 for success, non-zero for failure)."]
    pub fn rkllm_abort(handle: LLMHandle) -> ::std::os::raw::c_int;
    #[doc = " @brief Checks if an LLM task is currently running.\n @param handle LLM handle.\n @return Status code (1 if a task is running)."]
    pub fn rkllm_is_running(handle: LLMHandle) -> ::std::os::raw::c_int;
    #[doc = " @brief Clear the key-value cache for a given LLM handle.\n\n This function is used to clear part or all of the KV cache.\n\n @param handle LLM handle.\n @param keep_system_prompt Flag indicating whether to retain the system prompt in the cache (1 to retain, 0 to clear).\n                           This flag is ignored if a specific range [start_pos, end_pos) is provided.\n @param start_pos Array of start positions (inclusive) of the KV cache ranges to clear, one per batch.\n @param end_pos   Array of end positions (exclusive) of the KV cache ranges to clear, one per batch.\n                  If both start_pos and end_pos are set to nullptr, the entire cache will be cleared and keep_system_prompt will take effect,\n                  If start_pos[i] < end_pos[i], only the specified range will be cleared, and keep_system_prompt will be ignored.\n @note: start_pos or end_pos is only valid when keep_history == 0 and the generation has been paused by returning 1 in the callback\n @return Status code (0 if cache was cleared successfully, non-zero otherwise)."]
    pub fn rkllm_clear_kv_cache(
        handle: LLMHandle,
        keep_system_prompt: ::std::os::raw::c_int,
        start_pos: *mut ::std::os::raw::c_int,
        end_pos: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    #[doc = " @brief Get the current size of the key-value cache for a given LLM handle.\n\n This function returns the total number of positions currently stored in the model's KV cache.\n\n @param handle LLM handle.\n @param cache_sizes Pointer to an array where the per-batch cache sizes will be stored.\n                    The array must be preallocated with space for `n_batch` elements."]
    pub fn rkllm_get_kv_cache_size(
        handle: LLMHandle,
        cache_sizes: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    #[doc = " @brief Sets the chat template for the LLM, including system prompt, prefix, and postfix.\n\n This function allows you to customize the chat template by providing a system prompt, a prompt prefix, and a prompt postfix.\n The system prompt is typically used to define the behavior or context of the language model,\n while the prefix and postfix are used to format the user input and output respectively.\n\n @param handle LLM handle.\n @param system_prompt The system prompt that defines the context or behavior of the language model.\n @param prompt_prefix The prefix added before the user input in the chat.\n @param prompt_postfix The postfix added after the user input in the chat.\n\n @return Status code (0 if the template was set successfully, non-zero for errors)."]
    pub fn rkllm_set_chat_template(
        handle: LLMHandle,
        system_prompt: *const ::std::os::raw::c_char,
        prompt_prefix: *const ::std::os::raw::c_char,
        prompt_postfix: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
    #[doc = " @brief Sets the function calling configuration for the LLM, including system prompt, tool definitions, and tool response token.\n\n @param handle LLM handle.\n @param system_prompt The system prompt that defines the context or behavior of the language model.\n @param tools A JSON-formatted string that defines the available functions, including their names, descriptions, and parameters.\n @param tool_response_str A unique tag used to identify function call results within a conversation. It acts as the marker tag,\n                          allowing tokenizer to recognize tool outputs separately from normal dialogue turns.\n @return Status code (0 if the configuration was set successfully, non-zero for errors)."]
    pub fn rkllm_set_function_tools(
        handle: LLMHandle,
        system_prompt: *const ::std::os::raw::c_char,
        tools: *const ::std::os::raw::c_char,
        tool_response_str: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
    #[doc = " @brief Sets the cross-attention parameters for the LLM decoder.\n\n @param handle LLM handle.\n @param cross_attn_params Pointer to the structure containing encoder-related input data\n                          used for cross-attention (see RKLLMCrossAttnParam for details).\n\n @return Status code (0 if the parameters were set successfully, non-zero for errors)."]
    pub fn rkllm_set_cross_attn_params(
        handle: LLMHandle,
        cross_attn_params: *mut RKLLMCrossAttnParam,
    ) -> ::std::os::raw::c_int;
}
