/* automatically generated by rust-bindgen 0.73.2 */

//! Runtime bindings: the symbols are resolved by `dlopen`/`libloading` at run time.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(clippy::missing_safety_doc)]
#![allow(rustdoc::broken_intra_doc_links)]
// bindgen's --dynamic-loading output predates edition 2024's stricter unsafe rules.
#![allow(unsafe_op_in_unsafe_fn)]
// @generated by regen-bindings.sh -- do not edit by hand.
use super::types::*;

pub struct RkllmRuntime {
    __library: ::libloading::Library,
    pub rkllm_createDefaultParam: unsafe extern "C" fn() -> RKLLMParam,
    pub rkllm_init: unsafe extern "C" fn(
        handle: *mut LLMHandle,
        param: *mut RKLLMParam,
        callback: *mut RKLLMCallback,
    ) -> ::std::os::raw::c_int,
    pub rkllm_load_lora: unsafe extern "C" fn(
        handle: LLMHandle,
        lora_adapter: *mut RKLLMLoraAdapter,
    ) -> ::std::os::raw::c_int,
    pub rkllm_load_prompt_cache: unsafe extern "C" fn(
        handle: LLMHandle,
        prompt_cache_path: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
    pub rkllm_release_prompt_cache:
        unsafe extern "C" fn(handle: LLMHandle) -> ::std::os::raw::c_int,
    pub rkllm_destroy: unsafe extern "C" fn(handle: LLMHandle) -> ::std::os::raw::c_int,
    pub rkllm_run: unsafe extern "C" fn(
        handle: LLMHandle,
        rkllm_input: *mut RKLLMInput,
        rkllm_infer_params: *mut RKLLMInferParam,
        userdata: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
    pub rkllm_run_async: unsafe extern "C" fn(
        handle: LLMHandle,
        rkllm_input: *mut RKLLMInput,
        rkllm_infer_params: *mut RKLLMInferParam,
        userdata: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
    pub rkllm_abort: unsafe extern "C" fn(handle: LLMHandle) -> ::std::os::raw::c_int,
    pub rkllm_is_running: unsafe extern "C" fn(handle: LLMHandle) -> ::std::os::raw::c_int,
    pub rkllm_clear_kv_cache: unsafe extern "C" fn(
        handle: LLMHandle,
        keep_system_prompt: ::std::os::raw::c_int,
        start_pos: *mut ::std::os::raw::c_int,
        end_pos: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
    pub rkllm_get_kv_cache_size: unsafe extern "C" fn(
        handle: LLMHandle,
        cache_sizes: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
    pub rkllm_set_chat_template: unsafe extern "C" fn(
        handle: LLMHandle,
        system_prompt: *const ::std::os::raw::c_char,
        prompt_prefix: *const ::std::os::raw::c_char,
        prompt_postfix: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
    pub rkllm_set_function_tools: unsafe extern "C" fn(
        handle: LLMHandle,
        system_prompt: *const ::std::os::raw::c_char,
        tools: *const ::std::os::raw::c_char,
        tool_response_str: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
    pub rkllm_set_cross_attn_params: unsafe extern "C" fn(
        handle: LLMHandle,
        cross_attn_params: *mut RKLLMCrossAttnParam,
    ) -> ::std::os::raw::c_int,
}
impl RkllmRuntime {
    pub unsafe fn new<P>(path: P) -> Result<Self, ::libloading::Error>
    where
        P: AsRef<::std::ffi::OsStr>,
    {
        let path = path.as_ref();
        let library = ::libloading::Library::new(path)?;
        Self::from_library(library)
    }
    pub unsafe fn from_library<L>(library: L) -> Result<Self, ::libloading::Error>
    where
        L: Into<::libloading::Library>,
    {
        let __library = library.into();
        let rkllm_createDefaultParam = __library
            .get(b"rkllm_createDefaultParam\0")
            .map(|sym| *sym)?;
        let rkllm_init = __library.get(b"rkllm_init\0").map(|sym| *sym)?;
        let rkllm_load_lora = __library.get(b"rkllm_load_lora\0").map(|sym| *sym)?;
        let rkllm_load_prompt_cache = __library
            .get(b"rkllm_load_prompt_cache\0")
            .map(|sym| *sym)?;
        let rkllm_release_prompt_cache = __library
            .get(b"rkllm_release_prompt_cache\0")
            .map(|sym| *sym)?;
        let rkllm_destroy = __library.get(b"rkllm_destroy\0").map(|sym| *sym)?;
        let rkllm_run = __library.get(b"rkllm_run\0").map(|sym| *sym)?;
        let rkllm_run_async = __library.get(b"rkllm_run_async\0").map(|sym| *sym)?;
        let rkllm_abort = __library.get(b"rkllm_abort\0").map(|sym| *sym)?;
        let rkllm_is_running = __library.get(b"rkllm_is_running\0").map(|sym| *sym)?;
        let rkllm_clear_kv_cache = __library.get(b"rkllm_clear_kv_cache\0").map(|sym| *sym)?;
        let rkllm_get_kv_cache_size = __library
            .get(b"rkllm_get_kv_cache_size\0")
            .map(|sym| *sym)?;
        let rkllm_set_chat_template = __library
            .get(b"rkllm_set_chat_template\0")
            .map(|sym| *sym)?;
        let rkllm_set_function_tools = __library
            .get(b"rkllm_set_function_tools\0")
            .map(|sym| *sym)?;
        let rkllm_set_cross_attn_params = __library
            .get(b"rkllm_set_cross_attn_params\0")
            .map(|sym| *sym)?;
        Ok(RkllmRuntime {
            __library,
            rkllm_createDefaultParam,
            rkllm_init,
            rkllm_load_lora,
            rkllm_load_prompt_cache,
            rkllm_release_prompt_cache,
            rkllm_destroy,
            rkllm_run,
            rkllm_run_async,
            rkllm_abort,
            rkllm_is_running,
            rkllm_clear_kv_cache,
            rkllm_get_kv_cache_size,
            rkllm_set_chat_template,
            rkllm_set_function_tools,
            rkllm_set_cross_attn_params,
        })
    }
    #[doc = " @brief Creates a default RKLLMParam structure with preset values.\n @return A default RKLLMParam structure."]
    pub unsafe fn rkllm_createDefaultParam(&self) -> RKLLMParam {
        (self.rkllm_createDefaultParam)()
    }
    #[doc = " @brief Initializes the LLM with the given parameters.\n @param handle Pointer to the LLM handle.\n @param param Configuration parameters for the LLM.\n @param callback Pointer to callback structure for LLM events.\n @return Status code (0 for success, non-zero for failure)."]
    pub unsafe fn rkllm_init(
        &self,
        handle: *mut LLMHandle,
        param: *mut RKLLMParam,
        callback: *mut RKLLMCallback,
    ) -> ::std::os::raw::c_int {
        (self.rkllm_init)(handle, param, callback)
    }
    #[doc = " @brief Loads a Lora adapter into the LLM.\n @param handle LLM handle.\n @param lora_adapter Pointer to the Lora adapter structure.\n @return Status code (0 for success, non-zero for failure)."]
    pub unsafe fn rkllm_load_lora(
        &self,
        handle: LLMHandle,
        lora_adapter: *mut RKLLMLoraAdapter,
    ) -> ::std::os::raw::c_int {
        (self.rkllm_load_lora)(handle, lora_adapter)
    }
    #[doc = " @brief Loads a prompt cache from a file.\n @param handle LLM handle.\n @param prompt_cache_path Path to the prompt cache file.\n @return Status code (0 for success, non-zero for failure)."]
    pub unsafe fn rkllm_load_prompt_cache(
        &self,
        handle: LLMHandle,
        prompt_cache_path: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        (self.rkllm_load_prompt_cache)(handle, prompt_cache_path)
    }
    #[doc = " @brief Releases the prompt cache from memory.\n @param handle LLM handle.\n @return Status code (0 for success, non-zero for failure)."]
    pub unsafe fn rkllm_release_prompt_cache(&self, handle: LLMHandle) -> ::std::os::raw::c_int {
        (self.rkllm_release_prompt_cache)(handle)
    }
    #[doc = " @brief Destroys the LLM instance and releases resources.\n @param handle LLM handle.\n @return Status code (0 for success, non-zero for failure)."]
    pub unsafe fn rkllm_destroy(&self, handle: LLMHandle) -> ::std::os::raw::c_int {
        (self.rkllm_destroy)(handle)
    }
    #[doc = " @brief Runs an LLM inference task synchronously.\n @param handle LLM handle.\n @param rkllm_input Input data for the LLM.\n @param rkllm_infer_params Parameters for the inference task.\n @param userdata Pointer to userdata for the result callback.\n        If userdata is not NULL, it will be used preferentially.\n        Otherwise, result_userdata will be used as fallback.\n @return Status code (0 for success, non-zero for failure)."]
    pub unsafe fn rkllm_run(
        &self,
        handle: LLMHandle,
        rkllm_input: *mut RKLLMInput,
        rkllm_infer_params: *mut RKLLMInferParam,
        userdata: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int {
        (self.rkllm_run)(handle, rkllm_input, rkllm_infer_params, userdata)
    }
    #[doc = " @brief Runs an LLM inference task asynchronously.\n @param handle LLM handle.\n @param rkllm_input Input data for the LLM.\n @param rkllm_infer_params Parameters for the inference task.\n @param userdata Pointer to userdata for the result callback.\n        If userdata is not NULL, it will be used preferentially.\n        Otherwise, result_userdata will be used as fallback.\n @return Status code (0 for success, non-zero for failure)."]
    pub unsafe fn rkllm_run_async(
        &self,
        handle: LLMHandle,
        rkllm_input: *mut RKLLMInput,
        rkllm_infer_params: *mut RKLLMInferParam,
        userdata: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int {
        (self.rkllm_run_async)(handle, rkllm_input, rkllm_infer_params, userdata)
    }
    #[doc = " @brief Aborts an ongoing LLM task.\n @param handle LLM handle.\n @return Status code (0 for success, non-zero for failure)."]
    pub unsafe fn rkllm_abort(&self, handle: LLMHandle) -> ::std::os::raw::c_int {
        (self.rkllm_abort)(handle)
    }
    #[doc = " @brief Checks if an LLM task is currently running.\n @param handle LLM handle.\n @return Status code (1 if a task is running)."]
    pub unsafe fn rkllm_is_running(&self, handle: LLMHandle) -> ::std::os::raw::c_int {
        (self.rkllm_is_running)(handle)
    }
    #[doc = " @brief Clear the key-value cache for a given LLM handle.\n\n This function is used to clear part or all of the KV cache.\n\n @param handle LLM handle.\n @param keep_system_prompt Flag indicating whether to retain the system prompt in the cache (1 to retain, 0 to clear).\n                           This flag is ignored if a specific range [start_pos, end_pos) is provided.\n @param start_pos Array of start positions (inclusive) of the KV cache ranges to clear, one per batch.\n @param end_pos   Array of end positions (exclusive) of the KV cache ranges to clear, one per batch.\n                  If both start_pos and end_pos are set to nullptr, the entire cache will be cleared and keep_system_prompt will take effect,\n                  If start_pos[i] < end_pos[i], only the specified range will be cleared, and keep_system_prompt will be ignored.\n @note: start_pos or end_pos is only valid when keep_history == 0 and the generation has been paused by returning 1 in the callback\n @return Status code (0 if cache was cleared successfully, non-zero otherwise)."]
    pub unsafe fn rkllm_clear_kv_cache(
        &self,
        handle: LLMHandle,
        keep_system_prompt: ::std::os::raw::c_int,
        start_pos: *mut ::std::os::raw::c_int,
        end_pos: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int {
        (self.rkllm_clear_kv_cache)(handle, keep_system_prompt, start_pos, end_pos)
    }
    #[doc = " @brief Get the current size of the key-value cache for a given LLM handle.\n\n This function returns the total number of positions currently stored in the model's KV cache.\n\n @param handle LLM handle.\n @param cache_sizes Pointer to an array where the per-batch cache sizes will be stored.\n                    The array must be preallocated with space for `n_batch` elements."]
    pub unsafe fn rkllm_get_kv_cache_size(
        &self,
        handle: LLMHandle,
        cache_sizes: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int {
        (self.rkllm_get_kv_cache_size)(handle, cache_sizes)
    }
    #[doc = " @brief Sets the chat template for the LLM, including system prompt, prefix, and postfix.\n\n This function allows you to customize the chat template by providing a system prompt, a prompt prefix, and a prompt postfix.\n The system prompt is typically used to define the behavior or context of the language model,\n while the prefix and postfix are used to format the user input and output respectively.\n\n @param handle LLM handle.\n @param system_prompt The system prompt that defines the context or behavior of the language model.\n @param prompt_prefix The prefix added before the user input in the chat.\n @param prompt_postfix The postfix added after the user input in the chat.\n\n @return Status code (0 if the template was set successfully, non-zero for errors)."]
    pub unsafe fn rkllm_set_chat_template(
        &self,
        handle: LLMHandle,
        system_prompt: *const ::std::os::raw::c_char,
        prompt_prefix: *const ::std::os::raw::c_char,
        prompt_postfix: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        (self.rkllm_set_chat_template)(handle, system_prompt, prompt_prefix, prompt_postfix)
    }
    #[doc = " @brief Sets the function calling configuration for the LLM, including system prompt, tool definitions, and tool response token.\n\n @param handle LLM handle.\n @param system_prompt The system prompt that defines the context or behavior of the language model.\n @param tools A JSON-formatted string that defines the available functions, including their names, descriptions, and parameters.\n @param tool_response_str A unique tag used to identify function call results within a conversation. It acts as the marker tag,\n                          allowing tokenizer to recognize tool outputs separately from normal dialogue turns.\n @return Status code (0 if the configuration was set successfully, non-zero for errors)."]
    pub unsafe fn rkllm_set_function_tools(
        &self,
        handle: LLMHandle,
        system_prompt: *const ::std::os::raw::c_char,
        tools: *const ::std::os::raw::c_char,
        tool_response_str: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        (self.rkllm_set_function_tools)(handle, system_prompt, tools, tool_response_str)
    }
    #[doc = " @brief Sets the cross-attention parameters for the LLM decoder.\n\n @param handle LLM handle.\n @param cross_attn_params Pointer to the structure containing encoder-related input data\n                          used for cross-attention (see RKLLMCrossAttnParam for details).\n\n @return Status code (0 if the parameters were set successfully, non-zero for errors)."]
    pub unsafe fn rkllm_set_cross_attn_params(
        &self,
        handle: LLMHandle,
        cross_attn_params: *mut RKLLMCrossAttnParam,
    ) -> ::std::os::raw::c_int {
        (self.rkllm_set_cross_attn_params)(handle, cross_attn_params)
    }
}
