/* automatically generated by rust-bindgen 0.73.2 */

//! C types of the RKLLM runtime, generated from `vendor/rkllm.h`.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(clippy::missing_safety_doc)]
#![allow(rustdoc::broken_intra_doc_links)]
// @generated by regen-bindings.sh -- do not edit by hand.

#[doc = " @typedef LLMHandle\n @brief A handle used to manage and interact with the large language model."]
pub type LLMHandle = *mut ::std::os::raw::c_void;
#[doc = " @brief Function pointer type for callback to get LLM embeddings\n @param userdata Pointer to user-defined data\n @param tokens Array of token IDs\n @param num_tokens Number of tokens in the tokens array\n @param embed Pointer to buffer that will store the embedding output\n @param len Length of the embedding buffer in bytes\n @return Returns 0 on success, non-zero value on failure"]
pub type LLMGetEmbedCallback = ::std::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::std::os::raw::c_void,
        tokens: *mut i32,
        num_tokens: u64,
        embed: *mut ::std::os::raw::c_void,
        len: u64,
    ) -> ::std::os::raw::c_int,
>;
#[doc = " @typedef LLMTokenizerCallback\n @brief Callback function to handle tokenization.\n @param userdata Pointer to user data for the callback.\n @param text Pointer to the input text.\n @param text_len Length of input text in bytes.\n @param tokens Pointer to the array of token IDs.\n @param n_tokens_max Max number of output tokens.\n @return Return token count (>=0) on success, negative value on error."]
pub type LLMTokenizerCallback = ::std::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::std::os::raw::c_void,
        text: *const ::std::os::raw::c_char,
        text_len: i32,
        tokens: *mut i32,
        n_tokens_max: i32,
    ) -> ::std::os::raw::c_int,
>;
#[doc = " @typedef LLMResultCallback\n @brief Callback function to handle LLM results.\n @param result Pointer to the LLM result.\n @param userdata Pointer to user data for the callback.\n @param state State of the LLM call (e.g., finished, error).\n @return int Return value indicating the handling status:\n         - 0: Continue inference normally.\n         - 1: Pause inference. If the user wants to modify or intervene in the result (e.g., editing output, injecting new prompt),\n              return 1 to suspend the current inference. Later, call `rkllm_run` with updated content to resume inference.\n         - 2: Release the current output buffer. This is useful when the current output is no longer needed and the user wants to\n              reclaim memory immediately, especially when using RKLLM_INFER_GET_LAST_HIDDEN_LAYER or RKLLM_INFER_GET_LOGITS modes.\n              In these modes, the output buffer may occupy a significant amount of memory, particularly for large vocabularies."]
pub type LLMResultCallback = ::std::option::Option<
    unsafe extern "C" fn(
        result: *mut RKLLMResult,
        userdata: *mut ::std::os::raw::c_void,
        state: LLMCallState,
    ) -> ::std::os::raw::c_int,
>;
#[repr(transparent)]
#[doc = " @enum LLMCallState\n @brief Describes the possible states of an LLM call."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct LLMCallState(pub ::std::os::raw::c_uint);
#[repr(transparent)]
#[doc = " @enum RKLLMInputType\n @brief Defines the types of inputs that can be fed into the LLM."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct RKLLMInputType(pub ::std::os::raw::c_uint);
#[repr(transparent)]
#[doc = " @enum RKLLMInferMode\n @brief Specifies the inference modes of the LLM."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct RKLLMInferMode(pub ::std::os::raw::c_uint);
#[doc = " @struct RKLLMExtendParam\n @brief The extend parameters for configuring an LLM instance."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMExtendParam {
    #[doc = "< base_domain_id"]
    pub base_domain_id: i32,
    #[doc = "< Indicates whether to query word embedding vectors from flash memory (1) or not (0)."]
    pub embed_flash: i8,
    #[doc = "< Number of CPUs enabled for inference."]
    pub enabled_cpus_num: i8,
    #[doc = "< Bitmask indicating which CPUs to enable for inference."]
    pub enabled_cpus_mask: u32,
    #[doc = "< Number of input samples processed concurrently in one forward pass. Set to >1 to enable batched inference. Default is 1."]
    pub n_batch: u8,
    #[doc = "< Whether to enable cross attention (1 to enable, 0 to disable)."]
    pub use_cross_attn: i8,
    #[doc = "< reserved"]
    pub reserved: [u8; 104usize],
}
#[doc = " @struct RKLLMParam\n @brief Defines the parameters for configuring an LLM instance."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMParam {
    #[doc = "< Path to the model file."]
    pub model_path: *const ::std::os::raw::c_char,
    #[doc = "< Maximum number of tokens in the context window."]
    pub max_context_len: i32,
    #[doc = "< Maximum number of new tokens to generate."]
    pub max_new_tokens: i32,
    #[doc = "< Top-K sampling parameter for token generation."]
    pub top_k: i32,
    pub n_keep: i32,
    #[doc = "< Top-P (nucleus) sampling parameter."]
    pub top_p: f32,
    #[doc = "< Sampling temperature, affecting the randomness of token selection."]
    pub temperature: f32,
    #[doc = "< Penalty for repeating tokens in generation."]
    pub repeat_penalty: f32,
    #[doc = "< Penalizes frequent tokens during generation."]
    pub frequency_penalty: f32,
    #[doc = "< Penalizes tokens based on their presence in the input."]
    pub presence_penalty: f32,
    #[doc = "< Mirostat sampling strategy flag (0 to disable)."]
    pub mirostat: i32,
    #[doc = "< Tau parameter for Mirostat sampling."]
    pub mirostat_tau: f32,
    #[doc = "< Eta parameter for Mirostat sampling."]
    pub mirostat_eta: f32,
    #[doc = "< Whether to skip special tokens during generation."]
    pub skip_special_token: bool,
    #[doc = "< Whether to ignore the end-of-sequence token (true to ignore, false to consider)."]
    pub ignore_eos_token: bool,
    #[doc = "< Whether to run inference asynchronously."]
    pub is_async: bool,
    #[doc = "< Extend parameters."]
    pub extend_param: RKLLMExtendParam,
}
#[doc = " @struct RKLLMLoraAdapter\n @brief Defines parameters for a Lora adapter used in model fine-tuning."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMLoraAdapter {
    #[doc = "< Path to the Lora adapter file."]
    pub lora_adapter_path: *const ::std::os::raw::c_char,
    #[doc = "< Name of the Lora adapter."]
    pub lora_adapter_name: *const ::std::os::raw::c_char,
    #[doc = "< Scaling factor for applying the Lora adapter."]
    pub scale: f32,
}
#[doc = " @struct RKLLMEmbedInput\n @brief Represents an embedding input to the LLM."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMEmbedInput {
    #[doc = "< Pointer to the embedding vector (of size n_tokens * n_embed)."]
    pub embed: *mut f32,
    #[doc = "< Number of tokens represented in the embedding."]
    pub n_tokens: usize,
}
#[doc = " @struct RKLLMTokenInput\n @brief Represents token input to the LLM."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMTokenInput {
    #[doc = "< Array of token IDs."]
    pub input_ids: *mut i32,
    #[doc = "< Number of tokens in the input."]
    pub n_tokens: usize,
}
#[doc = " @struct RKLLMMultiModalInput\n @brief Represents multimodal input (e.g., text and image)."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMMultiModalInput {
    #[doc = "< Text prompt input."]
    pub prompt: *mut ::std::os::raw::c_char,
    pub image: RKLLMMultiModalInput__bindgen_ty_1,
    pub video: RKLLMMultiModalInput__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMMultiModalInput__bindgen_ty_1 {
    #[doc = "< Embedding of the image (size: n_image * n_image_tokens * embedding_dim * sizeof(float32))."]
    pub image_embed: *mut f32,
    #[doc = "< Number of image tokens."]
    pub n_image_tokens: usize,
    #[doc = "< Number of images."]
    pub n_image: usize,
    #[doc = "< Start tag for image in multimodal input."]
    pub image_start: *const ::std::os::raw::c_char,
    #[doc = "< End tag for image in multimodal input."]
    pub image_end: *const ::std::os::raw::c_char,
    #[doc = "< Content tag for image in multimodal input."]
    pub image_content: *const ::std::os::raw::c_char,
    #[doc = "< Width of image."]
    pub image_width: usize,
    #[doc = "< Height of image."]
    pub image_height: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMMultiModalInput__bindgen_ty_2 {
    #[doc = "< Embedding of the video (size: n_video * n_frame_per_video * n_frame_tokens * embedding_dim * sizeof(float32))."]
    pub video_embed: *mut f32,
    #[doc = "< Number of frame tokens."]
    pub n_frame_tokens: usize,
    #[doc = "< Number of frames per video."]
    pub n_frame_per_video: usize,
    #[doc = "< Number of video."]
    pub n_video: usize,
    #[doc = "< Start tag for video in multimodal input."]
    pub video_start: *const ::std::os::raw::c_char,
    #[doc = "< End tag for video in multimodal input."]
    pub video_end: *const ::std::os::raw::c_char,
    #[doc = "< Content tag for video in multimodal input."]
    pub video_content: *const ::std::os::raw::c_char,
    #[doc = "< Width of frame."]
    pub frame_width: usize,
    #[doc = "< Height of frame."]
    pub frame_height: usize,
}
#[doc = " @struct RKLLMInput\n @brief Represents different types of input to the LLM via a union."]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct RKLLMInput {
    #[doc = "< Message role: \"user\" (user input), \"tool\" (function result)"]
    pub role: *const ::std::os::raw::c_char,
    #[doc = "< Controls whether \"thinking mode\" is enabled for the Qwen3 model."]
    pub enable_thinking: bool,
    #[doc = "< Specifies the type of input provided (e.g., prompt, token, embed, multimodal)."]
    pub input_type: RKLLMInputType,
    pub __bindgen_anon_1: RKLLMInput__bindgen_ty_1,
}
#[doc = " @struct RKLLMLoraParam\n @brief Structure defining parameters for Lora adapters."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMLoraParam {
    #[doc = "< Name of the Lora adapter."]
    pub lora_adapter_name: *const ::std::os::raw::c_char,
}
#[doc = " @struct RKLLMPromptCacheParam\n @brief Structure to define parameters for caching prompts."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMPromptCacheParam {
    #[doc = "< Flag to indicate whether to save the prompt cache (0 = don't save, 1 = save)."]
    pub save_prompt_cache: ::std::os::raw::c_int,
    #[doc = "< Path to the prompt cache file."]
    pub prompt_cache_path: *const ::std::os::raw::c_char,
}
#[doc = " @struct RKLLMCrossAttnParam\n @brief Structure holding parameters for cross-attention inference.\n\n This structure is used when performing cross-attention in the decoder.\n It provides the encoder output (key/value caches), position indices,\n and attention mask.\n\n - `encoder_k_cache` must be stored in contiguous memory with layout:\n   [num_layers][num_tokens][num_kv_heads][head_dim]\n - `encoder_v_cache` must be stored in contiguous memory with layout:\n   [num_layers][num_kv_heads][head_dim][num_tokens]"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMCrossAttnParam {
    #[doc = "< Pointer to encoder key cache (size: num_layers * num_tokens * num_kv_heads * head_dim)."]
    pub encoder_k_cache: *mut f32,
    #[doc = "< Pointer to encoder value cache (size: num_layers * num_kv_heads * head_dim * num_tokens)."]
    pub encoder_v_cache: *mut f32,
    #[doc = "< Pointer to encoder attention mask (array of size num_tokens)."]
    pub encoder_mask: *mut f32,
    #[doc = "< Pointer to encoder token positions (array of size num_tokens)."]
    pub encoder_pos: *mut i32,
    #[doc = "< Number of tokens in the encoder sequence."]
    pub num_tokens: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMSamplingParam {
    #[doc = "< Top-K sampling parameter for token generation."]
    pub top_k: i32,
    #[doc = "< Top-P (nucleus) sampling parameter."]
    pub top_p: f32,
    #[doc = "< Sampling temperature, affecting the randomness of token selection."]
    pub temperature: f32,
    #[doc = "< Penalty for repeating tokens in generation."]
    pub repeat_penalty: f32,
    #[doc = "< Penalizes frequent tokens during generation."]
    pub frequency_penalty: f32,
    #[doc = "< Penalizes tokens based on their presence in the input."]
    pub presence_penalty: f32,
    #[doc = "< Mirostat sampling strategy flag (0 to disable)."]
    pub mirostat: i32,
    #[doc = "< Tau parameter for Mirostat sampling."]
    pub mirostat_tau: f32,
    #[doc = "< Eta parameter for Mirostat sampling."]
    pub mirostat_eta: f32,
}
#[doc = " @struct RKLLMInferParam\n @brief Structure for defining parameters during inference."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMInferParam {
    #[doc = "< Inference mode (e.g., generate or get last hidden layer)."]
    pub mode: RKLLMInferMode,
    #[doc = "< Pointer to Lora adapter parameters."]
    pub lora_params: *mut RKLLMLoraParam,
    #[doc = "< Pointer to prompt cache parameters."]
    pub prompt_cache_params: *mut RKLLMPromptCacheParam,
    #[doc = "< Pointer to sampling parameters. If set, overrides the sampling params from RKLLMParam for this run."]
    pub sampling_params: *mut RKLLMSamplingParam,
    pub keep_history: ::std::os::raw::c_int,
    #[doc = "< Maximum number of new tokens to generate. It will replace the value set in RKLLMParam during init. Set to <=0 to use the init value."]
    pub max_new_tokens: i32,
}
#[doc = " @struct RKLLMResultLastHiddenLayer\n @brief Structure to hold the hidden states from the last layer."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMResultLastHiddenLayer {
    #[doc = "< Pointer to the hidden states (of size num_tokens * embd_size)."]
    pub hidden_states: *const f32,
    #[doc = "< Size of the embedding vector."]
    pub embd_size: ::std::os::raw::c_int,
    #[doc = "< Number of tokens for which hidden states are stored."]
    pub num_tokens: ::std::os::raw::c_int,
}
#[doc = " @struct RKLLMResultLogits\n @brief Structure to hold the logits."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMResultLogits {
    #[doc = "< Pointer to the logits (of size num_tokens * vocab_size)."]
    pub logits: *const f32,
    #[doc = "< Size of the vocab."]
    pub vocab_size: ::std::os::raw::c_int,
    #[doc = "< Number of tokens for which logits are stored."]
    pub num_tokens: ::std::os::raw::c_int,
}
#[doc = " @struct RKLLMPerfStat\n @brief Structure to hold performance statistics for prefill and generate stages."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMPerfStat {
    #[doc = "< Total time taken for the prefill stage in milliseconds."]
    pub prefill_time_ms: f32,
    #[doc = "< Number of tokens processed during the prefill stage."]
    pub prefill_tokens: ::std::os::raw::c_int,
    #[doc = "< Total time taken for the generate stage in milliseconds."]
    pub generate_time_ms: f32,
    #[doc = "< Number of tokens processed during the generate stage."]
    pub generate_tokens: ::std::os::raw::c_int,
    #[doc = "< VmHWM resident memory usage during inference, in megabytes."]
    pub memory_usage_mb: f32,
}
#[doc = " @struct RKLLMResult\n @brief Structure to represent the result of LLM inference."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMResult {
    #[doc = "< Generated text result."]
    pub text: *const ::std::os::raw::c_char,
    #[doc = "< ID of the generated token."]
    pub token_id: i32,
    #[doc = "< Hidden states of the last layer (if requested)."]
    pub last_hidden_layer: RKLLMResultLastHiddenLayer,
    #[doc = "< Model output logits."]
    pub logits: RKLLMResultLogits,
    #[doc = "< Pointer to performance statistics (prefill and generate)."]
    pub perf: RKLLMPerfStat,
}
#[doc = " @struct RKLLMCallback\n @brief Structure to hold callback functions for LLM operations."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RKLLMCallback {
    #[doc = "< Callback for results returned by the LLM."]
    pub result_callback: LLMResultCallback,
    #[doc = "< Userdata for LLMResultCallback."]
    pub result_userdata: *mut ::std::os::raw::c_void,
    #[doc = "< Optional: required when model has no internal tokenizer."]
    pub tokenizer_callback: LLMTokenizerCallback,
    #[doc = "< Userdata for LLMTokenizerCallback."]
    pub tokenizer_userdata: *mut ::std::os::raw::c_void,
    #[doc = "< Optional: Only required when model has no internal embedding layer."]
    pub embed_callback: LLMGetEmbedCallback,
    #[doc = "< Userdata for LLMGetEmbedCallback."]
    pub embed_userdata: *mut ::std::os::raw::c_void,
}
pub const CPU0: u32 = 1;
pub const CPU1: u32 = 2;
pub const CPU2: u32 = 4;
pub const CPU3: u32 = 8;
pub const CPU4: u32 = 16;
pub const CPU5: u32 = 32;
pub const CPU6: u32 = 64;
pub const CPU7: u32 = 128;
#[repr(C)]
#[derive(Copy, Clone)]
pub union RKLLMInput__bindgen_ty_1 {
    #[doc = "< Text prompt input if input_type is RKLLM_INPUT_PROMPT."]
    pub prompt_input: *const ::std::os::raw::c_char,
    #[doc = "< Embedding input if input_type is RKLLM_INPUT_EMBED."]
    pub embed_input: RKLLMEmbedInput,
    #[doc = "< Token input if input_type is RKLLM_INPUT_TOKEN."]
    pub token_input: RKLLMTokenInput,
    #[doc = "< Multimodal input if input_type is RKLLM_INPUT_MULTIMODAL."]
    pub multimodal_input: RKLLMMultiModalInput,
}
impl LLMCallState {
    #[doc = "< The LLM call is in a normal running state."]
    pub const RKLLM_RUN_NORMAL: LLMCallState = LLMCallState(0);
    #[doc = "< The LLM call is waiting for complete UTF-8 encoded character."]
    pub const RKLLM_RUN_WAITING: LLMCallState = LLMCallState(1);
    #[doc = "< The LLM call has finished execution."]
    pub const RKLLM_RUN_FINISH: LLMCallState = LLMCallState(2);
    #[doc = "< An error occurred during the LLM call."]
    pub const RKLLM_RUN_ERROR: LLMCallState = LLMCallState(3);
}
impl RKLLMInputType {
    #[doc = "< Input is a text prompt."]
    pub const RKLLM_INPUT_PROMPT: RKLLMInputType = RKLLMInputType(0);
    #[doc = "< Input is a sequence of tokens."]
    pub const RKLLM_INPUT_TOKEN: RKLLMInputType = RKLLMInputType(1);
    #[doc = "< Input is an embedding vector."]
    pub const RKLLM_INPUT_EMBED: RKLLMInputType = RKLLMInputType(2);
    #[doc = "< Input is multimodal (e.g., text and image)."]
    pub const RKLLM_INPUT_MULTIMODAL: RKLLMInputType = RKLLMInputType(3);
}
impl RKLLMInferMode {
    #[doc = "< The LLM generates text based on input."]
    pub const RKLLM_INFER_GENERATE: RKLLMInferMode = RKLLMInferMode(0);
    #[doc = "< The LLM retrieves the last hidden layer for further processing."]
    pub const RKLLM_INFER_GET_LAST_HIDDEN_LAYER: RKLLMInferMode = RKLLMInferMode(1);
    #[doc = "< The LLM retrieves logits for further processing."]
    pub const RKLLM_INFER_GET_LOGITS: RKLLMInferMode = RKLLMInferMode(2);
}
